import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUserCircle, faListAlt } from "@fortawesome/free-regular-svg-icons";
import { faList } from "@fortawesome/free-solid-svg-icons";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full bg-white flex justify-center">
          <div className=" w-4/5 h-20 flex flex-row  items-center justify-between pr-10">
            <div className="text-orange-500 font-bold text-xl">
              Device Direct<span className="font-normal text-base">.com</span>
            </div>
            <div >
              <input type="search" placeholder="What are you looking for..." id="searchinput"
                className="peer relative h-10 w-80 rounded border border-slate-200 px-4 pr-12 text-sm
                 text-slate-500 outline-none transition-all autofill:bg-white invalid:border-pink-500
                  invalid:text-pink-500 focus:border-orange-500
                   invalid:focus:border-pink-500 focus-visible:outline-none disabled:cursor-not-allowed disabled:bg-slate-50
                    disabled:text-slate-400"
              ></input>

              <button className="items-center justify-center h-10 gap-2 px-6 text-sm font-medium tracking-wide text-white transition duration-300 rounded-r-full  
              focus-visible:outline-none whitespace-nowrap bg-orange-500 hover:bg-orange-600 focus:bg-orange-700 disabled:cursor-not-allowed
               disabled:border-orange-300 disabled:bg-orange-300 disabled:shadow-none">
                <span>Search</span>
              </button>

            </div>
            <div className="flex flex-row justify-center gap-7 h-full items-center">
              <div className="flex flex-row h-full items-center gap-2">
                <FontAwesomeIcon icon={faUserCircle} className="text-gray-600 h-1/2 " fixedWidth />
                <span>Sign in</span>
              </div>
              <button className="inline-flex h-10 items-center justify-center gap-2 whitespace-nowrap rounded-full bg-orange-500 px-5 text-sm font-medium tracking-wide text-white shadow-md shadow-orange-200 transition duration-300 hover:bg-orange-600 hover:shadow-sm hover:shadow-orange-200 focus:bg-orange-700 focus:shadow-sm focus:shadow-orange-200 focus-visible:outline-none disabled:cursor-not-allowed disabled:border-orange-300 disabled:bg-orange-300 disabled:shadow-none">
                <span>Sign up</span>
              </button>

            </div>
          </div>

        </div>
        <div className="w-full bg-white border-t-gray-200 border-t-1 flex justify-center border-b-1 border-b-gray-500">
          <div className=" w-4/5 h-10 flex flex-row  items-center gap-5">
            <div className="flex flex-row items-center gap-1 border-b-2 border-b-white">
              <FontAwesomeIcon icon={faList} className="w-4 text-gray-700" />
              <span>All categories</span>
            </div>
            <div className="border-b-2 border-b-white hover:border-b-2 hover:border-b-gray-800">

              <span>Featured selections</span>
            </div>
            <div className="border-b-2 border-b-white">

              <span>Trade Assurance</span>
            </div>
          </div>
        </div>
        <div className="flex flex-col w-ful">
          {children}
        </div>

      </body>
    </html>
  );
}
